import { STATUS } from '@hydrooj/utils/lib/status';

export const VERDICT = {
    RUNTIME_ERROR: STATUS.STATUS_RUNTIME_ERROR,
    WRONG_ANSWER: STATUS.STATUS_WRONG_ANSWER,
    OK: STATUS.STATUS_ACCEPTED,
    TIME_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEEDED: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    IDLENESS_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    ACCEPTED: STATUS.STATUS_ACCEPTED,
    'PRESENTATION ERROR': STATUS.STATUS_WRONG_ANSWER,
    'WRONG ANSWER': STATUS.STATUS_WRONG_ANSWER,
    'RUNTIME ERROR': STATUS.STATUS_RUNTIME_ERROR,
    'TIME LIMIT EXCEEDED': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    'MEMORY LIMIT EXCEEDED': STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    'OUTPUT LIMIT EXCEEDED': STATUS.STATUS_OUTPUT_LIMIT_EXCEEDED,
    'IDLENESS LIMIT EXCEEDED': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    'EXTRA TEST PASSED': STATUS.STATUS_ACCEPTED,
    'COMPILE ERROR': STATUS.STATUS_COMPILE_ERROR,
    'RUNNING & JUDGING': STATUS.STATUS_JUDGING,
};
