import { STATUS } from '@hydrooj/utils/lib/status';

export const VERDICT = {
    RUNTIME_ERROR: STATUS.STATUS_RUNTIME_ERROR,
    WRONG_ANSWER: STATUS.STATUS_WRONG_ANSWER,
    OK: STATUS.STATUS_ACCEPTED,
    TIME_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEEDED: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    IDLENESS_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    ACCEPTED: STATUS.STATUS_ACCEPTED,
    'PRESENTATION ERROR': STATUS.STATUS_WRONG_ANSWER,
    'WRONG ANSWER': STATUS.STATUS_WRONG_ANSWER,
    'RUNTIME ERROR': STATUS.STATUS_RUNTIME_ERROR,
    'TIME LIMIT EXCEEDED': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    'MEMORY LIMIT EXCEEDED': STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    'OUTPUT LIMIT EXCEEDED': STATUS.STATUS_OUTPUT_LIMIT_EXCEEDED,
    'IDLENESS LIMIT EXCEEDED': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    'EXTRA TEST PASSED': STATUS.STATUS_ACCEPTED,
    'COMPILE ERROR': STATUS.STATUS_COMPILE_ERROR,
    'RUNNING & JUDGING': STATUS.STATUS_JUDGING,

    Accepted: STATUS.STATUS_ACCEPTED,
    'Wrong answer': STATUS.STATUS_WRONG_ANSWER,
    'Runtime error': STATUS.STATUS_RUNTIME_ERROR,
    'Time limit exceeded': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    'Memory limit exceeded': STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    'Idleness limit exceeded': STATUS.STATUS_TIME_LIMIT_EXCEEDED,

    'Happy New Year!': STATUS.STATUS_ACCEPTED, // Codeforces

    // Vjudge
    QUEUEING: STATUS.STATUS_COMPILING,
    PENDING: STATUS.STATUS_COMPILING,
    SUBMITTED: STATUS.STATUS_COMPILING,
    JUDGING: STATUS.STATUS_JUDGING,
    AC: STATUS.STATUS_ACCEPTED,
    WA: STATUS.STATUS_WRONG_ANSWER,
    RE: STATUS.STATUS_RUNTIME_ERROR,
    CE: STATUS.STATUS_COMPILE_ERROR,
    PE: STATUS.STATUS_WRONG_ANSWER,
    TLE: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MLE: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    OLE: STATUS.STATUS_WRONG_ANSWER,
    FAILED_OTHER: STATUS.STATUS_SYSTEM_ERROR,
    SUBMIT_FAILED_PERM: STATUS.STATUS_SYSTEM_ERROR,
    SUBMIT_FAILED_TEMP: STATUS.STATUS_SYSTEM_ERROR,
};
