module.exports = {
    blacklist: require('./blacklist'),
    builtin: require('./builtin'),
    contest: require('./contest'),
    document: require('./document'),
    opcount: require('./opcount'),
    problem: require('./problem'),
    record: require('./record'),
    solution: require('./solution'),
    system: require('./system'),
    token: require('./token'),
    training: require('./training'),
    user: require('./user'),
    task: require('./task'),
    message: require('./message'),
    setting: require('./setting'),
    file: require('./file'),
};
