let privileges = {
    PRIV_NONE: 0,
    PRIV_ALL: -1,
    PRIV_SET_PRIV: 1 << 0,
    PRIV_SET_PERM: 1 << 1,
    PRIV_USER_PROFILE: 1 << 2,
    PRIV_REGISTER_USER: 1 << 3,
    PRIV_READ_PROBLEM_DATA: 1 << 4,
    PRIV_READ_PRETEST_DATA: 1 << 5,
    PRIV_READ_PRETEST_DATA_SELF: 1 << 6,
    PRIV_READ_RECORD_CODE: 1 << 7,
    PRIV_VIEW_HIDDEN_RECORD: 1 << 8,
    PRIV_WRITE_RECORD: 1 << 9,
    PRIV_CREATE_DOMAIN: 1 << 10,
    PRIV_VIEW_ALL_DOMAIN: 1 << 11,
    PRIV_MANAGE_ALL_DOMAIN: 1 << 12,
    PRIV_REJUDGE: 1 << 13,
    PRIV_VIEW_USER_SECRET: 1 << 14,
    PRIV_VIEW_JUDGE_STATISTICS: 1 << 15,
    PRIV_CREATE_FILE: 1 << 16,
    PRIV_UNLIMITED_QUOTA: 1 << 17,
    PRIV_DELETE_FILE: 1 << 18,
    PRIV_DELETE_FILE_SELF: 1 << 19
};
privileges.PRIV_DEFAULT =
    privileges.PRIV_USER_PROFILE | privileges.PRIV_CREATE_DOMAIN
    | privileges.PRIV_CREATE_FILE | privileges.PRIV_DELETE_FILE_SELF;
privileges.PRIV_JUDGE =
    privileges.PRIV_USER_PROFILE | privileges.PRIV_VIEW_ALL_DOMAIN
    | privileges.PRIV_READ_PROBLEM_DATA | privileges.PRIV_READ_PRETEST_DATA
    | privileges.PRIV_READ_RECORD_CODE | privileges.PRIV_WRITE_RECORD;
module.exports = privileges;